"""
DegradationRecord ORM model.

Stores physics-based material degradation predictions for an asset.
Generated by the Material Degradation Engine (Phase 4).
Each record represents a point-in-time prediction snapshot.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any

from sqlalchemy import Float, ForeignKey, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.models.base import Base, TimestampedMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from backend.app.models.asset import Asset


class DegradationRecord(UUIDPrimaryKeyMixin, TimestampedMixin, Base):
    """
    Material degradation prediction record.

    Contains outputs from physics models:
    - Carbonation depth (Papadakis equation)
    - Chloride content (Fick's 2nd law diffusion)
    - Corrosion probability
    - Remaining Service Life estimate

    Linked to an asset (not an inspection) because degradation is a continuous
    process that can be modelled independently of individual inspections.
    """

    __tablename__ = "degradation_records"

    # ── Foreign key ────────────────────────────────────────────────────────────
    asset_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("assets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Physics model outputs ─────────────────────────────────────────────────
    remaining_service_life_years: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        doc="Estimated remaining structural service life (years from prediction date)."
    )
    corrosion_probability: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        doc="Probability of active rebar corrosion [0.0, 1.0]."
    )
    carbonation_depth_mm: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        doc="Predicted carbonation front depth in mm."
    )
    chloride_content_pct: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        doc="Predicted chloride content at rebar depth (% by weight of cement)."
    )
    time_to_maintenance_years: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        doc="Predicted years until maintenance intervention is required."
    )

    # ── Time-series forecast data (for chart rendering in Phase 6) ────────────
    forecast_curves: Mapped[dict[str, Any] | None] = mapped_column(
        JSON, nullable=True,
        doc=(
            "JSON forecast data for plotting. "
            "Structure: {'years': [...], 'carbonation_mm': [...], 'corrosion_prob': [...]}."
        ),
    )

    # ── Model inputs (for reproducibility / audit) ────────────────────────────
    model_inputs: Mapped[dict[str, Any] | None] = mapped_column(
        JSON, nullable=True,
        doc="Input parameters used to generate this prediction (exposure class, w/c ratio, etc.)."
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Relationship ──────────────────────────────────────────────────────────
    asset: Mapped[Asset] = relationship(
        "Asset", back_populates="degradation_records"
    )

    def __repr__(self) -> str:
        return (
            f"<DegradationRecord id={self.id!r} asset={self.asset_id!r} "
            f"rsl={self.remaining_service_life_years}yr>"
        )
